export const blogsData = [
    {
        id: 1,
        title: "HTML",
        body:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum ratione, ex eligendi tempore fuga ab voluptate optio laborum dicta, magnam illo at illum officiis, dolorem commodi exercitationem consectetur enim quod explicabo nisi error tenetur modi. Voluptates temporibus ad quisquam nam. Repudiandae adipisci blanditiis inventore, tenetur repellat assumenda eligendi beatae debitis perspiciatis labore ducimus eius deleniti dolorem illum molestiae ipsam voluptatum vitae, odit necessitatibus. At ex voluptatum obcaecati esse! Accusantium vel eveniet deserunt dolores corporis beatae quasi, inventore quam ex voluptatum! Qui dolore quam doloribus, neque itaque vitae perspiciatis temporibus doloremque hic odio quis fugiat deleniti voluptatem a expedita ab error. Culpa dignissimos veritatis consequatur vero! Iure repellendus nostrum est! Pariatur sapiente, iusto vel totam est voluptas quia saepe optio aperiam? Explicabo iste sint eaque blanditiis aliquam optio laborum assumenda nobis ducimus. Doloribus cum, exercitationem facere repudiandae ab sit, tenetur asperiores ad non iure nulla nam eum qui in iste tempora."
    },
    {
        id: 2,
        title: "CSS",
        body:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum ratione, ex eligendi tempore fuga ab voluptate optio laborum dicta, magnam illo at illum officiis, dolorem commodi exercitationem consectetur enim quod explicabo nisi error tenetur modi. Voluptates temporibus ad quisquam nam. Repudiandae adipisci blanditiis inventore, tenetur repellat assumenda eligendi beatae debitis perspiciatis labore ducimus eius deleniti dolorem illum molestiae ipsam voluptatum vitae, odit necessitatibus. At ex voluptatum obcaecati esse! Accusantium vel eveniet deserunt dolores corporis beatae quasi, inventore quam ex voluptatum! Qui dolore quam doloribus, neque itaque vitae perspiciatis temporibus doloremque hic odio quis fugiat deleniti voluptatem a expedita ab error. Culpa dignissimos veritatis consequatur vero! Iure repellendus nostrum est! Pariatur sapiente, iusto vel totam est voluptas quia saepe optio aperiam? Explicabo iste sint eaque blanditiis aliquam optio laborum assumenda nobis ducimus. Doloribus cum, exercitationem facere repudiandae ab sit, tenetur asperiores ad non iure nulla nam eum qui in iste tempora."
    },
    {
        id: 3,
        title: "React",
        body:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum ratione, ex eligendi tempore fuga ab voluptate optio laborum dicta, magnam illo at illum officiis, dolorem commodi exercitationem consectetur enim quod explicabo nisi error tenetur modi. Voluptates temporibus ad quisquam nam. Repudiandae adipisci blanditiis inventore, tenetur repellat assumenda eligendi beatae debitis perspiciatis labore ducimus eius deleniti dolorem illum molestiae ipsam voluptatum vitae, odit necessitatibus. At ex voluptatum obcaecati esse! Accusantium vel eveniet deserunt dolores corporis beatae quasi, inventore quam ex voluptatum! Qui dolore quam doloribus, neque itaque vitae perspiciatis temporibus doloremque hic odio quis fugiat deleniti voluptatem a expedita ab error. Culpa dignissimos veritatis consequatur vero! Iure repellendus nostrum est! Pariatur sapiente, iusto vel totam est voluptas quia saepe optio aperiam? Explicabo iste sint eaque blanditiis aliquam optio laborum assumenda nobis ducimus. Doloribus cum, exercitationem facere repudiandae ab sit, tenetur asperiores ad non iure nulla nam eum qui in iste tempora."
    },
    {
        id: 4,
        title: "JS",
        body:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum ratione, ex eligendi tempore fuga ab voluptate optio laborum dicta, magnam illo at illum officiis, dolorem commodi exercitationem consectetur enim quod explicabo nisi error tenetur modi. Voluptates temporibus ad quisquam nam. Repudiandae adipisci blanditiis inventore, tenetur repellat assumenda eligendi beatae debitis perspiciatis labore ducimus eius deleniti dolorem illum molestiae ipsam voluptatum vitae, odit necessitatibus. At ex voluptatum obcaecati esse! Accusantium vel eveniet deserunt dolores corporis beatae quasi, inventore quam ex voluptatum! Qui dolore quam doloribus, neque itaque vitae perspiciatis temporibus doloremque hic odio quis fugiat deleniti voluptatem a expedita ab error. Culpa dignissimos veritatis consequatur vero! Iure repellendus nostrum est! Pariatur sapiente, iusto vel totam est voluptas quia saepe optio aperiam? Explicabo iste sint eaque blanditiis aliquam optio laborum assumenda nobis ducimus. Doloribus cum, exercitationem facere repudiandae ab sit, tenetur asperiores ad non iure nulla nam eum qui in iste tempora."
    },
    {
        id: 5,
        title: "Node js",
        body:" Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum ratione, ex eligendi tempore fuga ab voluptate optio laborum dicta, magnam illo at illum officiis, dolorem commodi exercitationem consectetur enim quod explicabo nisi error tenetur modi. Voluptates temporibus ad quisquam nam. Repudiandae adipisci blanditiis inventore, tenetur repellat assumenda eligendi beatae debitis perspiciatis labore ducimus eius deleniti dolorem illum molestiae ipsam voluptatum vitae, odit necessitatibus. At ex voluptatum obcaecati esse! Accusantium vel eveniet deserunt dolores corporis beatae quasi, inventore quam ex voluptatum! Qui dolore quam doloribus, neque itaque vitae perspiciatis temporibus doloremque hic odio quis fugiat deleniti voluptatem a expedita ab error. Culpa dignissimos veritatis consequatur vero! Iure repellendus nostrum est! Pariatur sapiente, iusto vel totam est voluptas quia saepe optio aperiam? Explicabo iste sint eaque blanditiis aliquam optio laborum assumenda nobis ducimus. Doloribus cum, exercitationem facere repudiandae ab sit, tenetur asperiores ad non iure nulla nam eum qui in iste tempora."
    },
]