import React from 'react'

const Home = () => {
  return (
    <div>
        <h1>Home</h1>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <h1>Home</h1>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <h1>Home</h1>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
        <p>Et occaecat duis velit nostrud sunt ut nisi magna eu proident id sint. Fugiat non laborum sint minim ex nulla ea nostrud irure nulla non dolor et amet. Sit veniam qui aute consectetur in in id qui reprehenderit veniam. Magna aliqua ex aliquip ipsum ad duis exercitation aliquip labore proident est non eiusmod ut. Voluptate laboris deserunt laborum nisi elit amet ea elit amet. Dolore sit ipsum voluptate magna sit Lorem eiusmod duis officia sunt ipsum magna nulla.</p>
    </div>
  )
}

export default Home