export const blogsData = [
  {
    id: 1,
    title: "HTML",
    body: "Cupidatat voluptate velit occaecat aliqua dolore exercitation irure dolore amet duis excepteur. Ut ex do aliqua culpa est proident tempor velit anim ipsum. Nulla mollit incididunt anim occaecat veniam ullamco. Officia elit nisi nisi occaecat pariatur sint. Excepteur non ex enim ad sint eiusmod nostrud cillum in ex do anim est. Voluptate dolore deserunt cillum aliquip pariatur anim cillum elit qui laboris esse reprehenderit.Pariatur et non do sit Lorem labore Lorem veniam magna qui ex mollit aliqua. Voluptate cillum sit quis excepteur. Aliqua exercitation fugiat consectetur aute amet qui consequat in duis magna elit ut. Sint in eu eiusmod eiusmod ea velit laboris dolore mollit consectetur id qui. Amet sunt magna eiusmod aliquip amet ex nulla. Culpa et consequat ad duis in est. Esse sint nostrud anim do tempor pariatur nulla qui cupidatat ad sit.Esse aliqua ullamco enim quis. Minim irure voluptate nulla nisi fugiat eu nisi Lorem duis enim ea velit velit ullamco. Sit adipisicing laborum labore non tempor sit cillum quis. Qui ut elit adipisicing cillum culpa nostrud dolore occaecat proident voluptate elit aute aliqua. Dolore cillum sunt laboris enim labore anim officia tempor voluptate. Et qui laborum qui ea ea et mollit excepteur excepteur consectetur. Qui nisi labore elit incididunt.",
  },
  {
    id: 2,
    title: "CSS",
    body: "Cupidatat voluptate velit occaecat aliqua dolore exercitation irure dolore amet duis excepteur. Ut ex do aliqua culpa est proident tempor velit anim ipsum. Nulla mollit incididunt anim occaecat veniam ullamco. Officia elit nisi nisi occaecat pariatur sint. Excepteur non ex enim ad sint eiusmod nostrud cillum in ex do anim est. Voluptate dolore deserunt cillum aliquip pariatur anim cillum elit qui laboris esse reprehenderit.Pariatur et non do sit Lorem labore Lorem veniam magna qui ex mollit aliqua. Voluptate cillum sit quis excepteur. Aliqua exercitation fugiat consectetur aute amet qui consequat in duis magna elit ut. Sint in eu eiusmod eiusmod ea velit laboris dolore mollit consectetur id qui. Amet sunt magna eiusmod aliquip amet ex nulla. Culpa et consequat ad duis in est. Esse sint nostrud anim do tempor pariatur nulla qui cupidatat ad sit.Esse aliqua ullamco enim quis. Minim irure voluptate nulla nisi fugiat eu nisi Lorem duis enim ea velit velit ullamco. Sit adipisicing laborum labore non tempor sit cillum quis. Qui ut elit adipisicing cillum culpa nostrud dolore occaecat proident voluptate elit aute aliqua. Dolore cillum sunt laboris enim labore anim officia tempor voluptate. Et qui laborum qui ea ea et mollit excepteur excepteur consectetur. Qui nisi labore elit incididunt.",
  },
  {
    id: 3,
    title: "REACT",
    body: "Cupidatat voluptate velit occaecat aliqua dolore exercitation irure dolore amet duis excepteur. Ut ex do aliqua culpa est proident tempor velit anim ipsum. Nulla mollit incididunt anim occaecat veniam ullamco. Officia elit nisi nisi occaecat pariatur sint. Excepteur non ex enim ad sint eiusmod nostrud cillum in ex do anim est. Voluptate dolore deserunt cillum aliquip pariatur anim cillum elit qui laboris esse reprehenderit.Pariatur et non do sit Lorem labore Lorem veniam magna qui ex mollit aliqua. Voluptate cillum sit quis excepteur. Aliqua exercitation fugiat consectetur aute amet qui consequat in duis magna elit ut. Sint in eu eiusmod eiusmod ea velit laboris dolore mollit consectetur id qui. Amet sunt magna eiusmod aliquip amet ex nulla. Culpa et consequat ad duis in est. Esse sint nostrud anim do tempor pariatur nulla qui cupidatat ad sit.Esse aliqua ullamco enim quis. Minim irure voluptate nulla nisi fugiat eu nisi Lorem duis enim ea velit velit ullamco. Sit adipisicing laborum labore non tempor sit cillum quis. Qui ut elit adipisicing cillum culpa nostrud dolore occaecat proident voluptate elit aute aliqua. Dolore cillum sunt laboris enim labore anim officia tempor voluptate. Et qui laborum qui ea ea et mollit excepteur excepteur consectetur. Qui nisi labore elit incididunt.",
  },
  {
    id: 4,
    title: "NODE_JS",
    body: "Cupidatat voluptate velit occaecat aliqua dolore exercitation irure dolore amet duis excepteur. Ut ex do aliqua culpa est proident tempor velit anim ipsum. Nulla mollit incididunt anim occaecat veniam ullamco. Officia elit nisi nisi occaecat pariatur sint. Excepteur non ex enim ad sint eiusmod nostrud cillum in ex do anim est. Voluptate dolore deserunt cillum aliquip pariatur anim cillum elit qui laboris esse reprehenderit.Pariatur et non do sit Lorem labore Lorem veniam magna qui ex mollit aliqua. Voluptate cillum sit quis excepteur. Aliqua exercitation fugiat consectetur aute amet qui consequat in duis magna elit ut. Sint in eu eiusmod eiusmod ea velit laboris dolore mollit consectetur id qui. Amet sunt magna eiusmod aliquip amet ex nulla. Culpa et consequat ad duis in est. Esse sint nostrud anim do tempor pariatur nulla qui cupidatat ad sit.Esse aliqua ullamco enim quis. Minim irure voluptate nulla nisi fugiat eu nisi Lorem duis enim ea velit velit ullamco. Sit adipisicing laborum labore non tempor sit cillum quis. Qui ut elit adipisicing cillum culpa nostrud dolore occaecat proident voluptate elit aute aliqua. Dolore cillum sunt laboris enim labore anim officia tempor voluptate. Et qui laborum qui ea ea et mollit excepteur excepteur consectetur. Qui nisi labore elit incididunt.",
  },
  {
    id: 4,
    title: "EXPRESS",
    body: "Cupidatat voluptate velit occaecat aliqua dolore exercitation irure dolore amet duis excepteur. Ut ex do aliqua culpa est proident tempor velit anim ipsum. Nulla mollit incididunt anim occaecat veniam ullamco. Officia elit nisi nisi occaecat pariatur sint. Excepteur non ex enim ad sint eiusmod nostrud cillum in ex do anim est. Voluptate dolore deserunt cillum aliquip pariatur anim cillum elit qui laboris esse reprehenderit.Pariatur et non do sit Lorem labore Lorem veniam magna qui ex mollit aliqua. Voluptate cillum sit quis excepteur. Aliqua exercitation fugiat consectetur aute amet qui consequat in duis magna elit ut. Sint in eu eiusmod eiusmod ea velit laboris dolore mollit consectetur id qui. Amet sunt magna eiusmod aliquip amet ex nulla. Culpa et consequat ad duis in est. Esse sint nostrud anim do tempor pariatur nulla qui cupidatat ad sit.Esse aliqua ullamco enim quis. Minim irure voluptate nulla nisi fugiat eu nisi Lorem duis enim ea velit velit ullamco. Sit adipisicing laborum labore non tempor sit cillum quis. Qui ut elit adipisicing cillum culpa nostrud dolore occaecat proident voluptate elit aute aliqua. Dolore cillum sunt laboris enim labore anim officia tempor voluptate. Et qui laborum qui ea ea et mollit excepteur excepteur consectetur. Qui nisi labore elit incididunt.",
  },
];
